<?php
$uInt_templates_uranium_menu["FSuAuth"]='Authorization';//Название модуля Авторизация в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuCat"]='Catalog';//Название модуля Каталог в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuDrive"]='Disk';//Название модуля Диск в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuEditor"]='Editor';//Название модуля Редактор в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuEvents"]='Events';//Название модуля События в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuForms"]='Forms';//Название модуля Формы в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuKnowbase"]='Knowledge base';//Название модуля База знаний в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuNavi"]='Menu';//Название модуля Меню в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuPeople"]='People';//Название модуля Наши сотрудники в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuSlider"]='Slider';//Название модуля Слайды в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuSup"]='Support';//Название модуля Поддержка в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuSubscr"]='Subscriptions';//Название модуля Подписки в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSauthavatars"]='Avatars users';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FScatavatars"]='Category images';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSartavatars"]='Images of articles';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSitemavatars"]='Product images';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSsectavatars"]='Section images';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSitempictures"]='Product images';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSfiles"]='Files';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSpageavatars"]='Page images';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSeventsfiles"]='Event files';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSeventstypesfiles"]='The image of the event type';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSfieldfiles"]='Form files';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSpeopleavatars"]='Photos of people';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSitemicons"]='Icons of menu items';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSslidesbg"]='Slide backgrounds';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FScomavatars"]='Company images';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSmsgsfiles"]='Query files';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSbyte"]='B';//Еденица измерения Байты
$uInt_templates_uranium_menu["FSKbyte"]='KB';//Еденица измерения Килобайты
$uInt_templates_uranium_menu["FSMbyte"]='MB';//Еденица измерения Мегабайты
$uInt_templates_uranium_menu["FSGbyte"]='GB';//Еденица измерения Гигабайты
$uInt_templates_uranium_menu["FSTbyte"]='TB';//Еденица измерения Терабайты