<?php
$uInt_templates_uranium_menu["FSuAuth"]='Авторизация';//Название модуля Авторизация в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuCat"]='Каталог';//Название модуля Каталог в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuDrive"]='Диск';//Название модуля Диск в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuEditor"]='Редактор';//Название модуля Редактор в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuEvents"]='События';//Название модуля События в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuForms"]='Формы';//Название модуля Формы в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuKnowbase"]='База знаний';//Название модуля База знаний в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuNavi"]='Меню';//Название модуля Меню в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuPeople"]='Наши сотрудники';//Название модуля Наши сотрудники в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuSlider"]='Слайды';//Название модуля Слайды в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuSup"]='Поддержка';//Название модуля Поддержка в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSuSubscr"]='Подписки и рассылки';//Название модуля Подписки в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSauthavatars"]='Аватарки пользователей';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FScatavatars"]='Изображения категорий';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSartavatars"]='Изображения статей';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSitemavatars"]='Изображения товаров';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSsectavatars"]='Изображения разделов';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSitempictures"]='Изображения товаров';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSfiles"]='Файлы';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSpageavatars"]='Изображения страниц';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSeventsfiles"]='Файлы событий';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSeventstypesfiles"]='Изображение типа события';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSfieldfiles"]='Файлы форм';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSpeopleavatars"]='Фото людей';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSitemicons"]='Иконки пунктов меню';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSslidesbg"]='Фоны слайдов';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FScomavatars"]='Изображения компаний';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSmsgsfiles"]='Файлы запросов';//Название подраздела модуля в таблице модального окна Размер сайта
$uInt_templates_uranium_menu["FSbyte"]='Б';//Еденица измерения Байты
$uInt_templates_uranium_menu["FSKbyte"]='Кб';//Еденица измерения Килобайты
$uInt_templates_uranium_menu["FSMbyte"]='Мб';//Еденица измерения Мегабайты
$uInt_templates_uranium_menu["FSGbyte"]='Гб';//Еденица измерения Гигабайты
$uInt_templates_uranium_menu["FSTbyte"]='Тб';//Еденица измерения Терабайты