<?php
$uInt_uEditor_setup_article["Close - btn txt"]='Закрыть';//Кнопка "Закрыть" в диалоге
$uInt_uEditor_setup_article["Save - btn txt"]='Сохранить';//Кнопка "Сохранить" в диалоге
$uInt_uEditor_setup_article["Basic page image - dg title"]='Основное изображение';//Заголовок диалога загрузчика основной картинки статьи
$uInt_uEditor_setup_article["Show image on current page - input label"]='Отображать изображение на этой странице?';//Подпись к полю "Отображать изображение на этой странице?"
$uInt_uEditor_setup_article["Show image on current page - input descr"]='Если снять, то на странице не будет отображаться, а будет только в виджетах и списках';//Описание к полю "Отображать изображение на этой странице?"
$uInt_uEditor_setup_article["Show image on pages - input label"]='Отображать изображения страниц на страницах текстов?';//Подпись к полю "Отображать изображения страниц на страницах статей?"
$uInt_uEditor_setup_article["Show image on pages - input descr"]='Если снять, то основные изображения текстов будут скрыты на всех страницах текстов';//Описание к полю "Отображать изображения страниц на страницах статей?"
$uInt_uEditor_setup_article["Basic image width on page - input label"]='Ширина изображения на этой странице';//Подпись к полю "Ширина изображения на этой странице"
$uInt_uEditor_setup_article["Basic image width on articles list - input label"]='Ширина изображения в списке текстов в рубрике (например список всех новостей)';//Подпись к полю "Ширина изображения в списке страниц в рубрике (например список всех новостей)"
$uInt_uEditor_setup_article["Basic image width in widget - input label"]='Ширина изображения в виджете рубрики (например новости на главной)';//Подпись к полю "Ширина изображения в виджете рубрики (например новости на главной)"
$uInt_uEditor_setup_article["Basic image description"]='Основное изображение отображается в различных виджетах на сайте. Например в списке новостей на главной странице.<br>Также оно может отображаться на самой странице.';//Описание основного изобрежения статьи
$uInt_uEditor_setup_article["Delete image - btn txt"]='Удалить изображение';//Кнопка "Удалить изображение" в диалоге редактора основного изображения статьи
$uInt_uEditor_setup_article["Short text - dg title"]='Краткий текст';//Заголовок диалога с редактором краткого текста страницы
$uInt_uEditor_setup_article["short text - input label"]='Краткий текст:';//Подпись к полю "Краткий текст:"
$uInt_uEditor_setup_article["Short text - description"]='Краткий текст отображается в различных виджетах на сайте. Например в списке новостей на главной странице.';//Описание к полю "Краткий текст:"
$uInt_uEditor_setup_article["Uploaded files - dg title"]='Загруженные файлы';//Заголовок диалога со списком файлов, загруженных к статье
$uInt_uEditor_setup_article["Insert to editor - btn txt"]='Вставить в редактор';//Текст кнопки "Вставить в редактор" - вставляет файл в редактор
$uInt_uEditor_setup_article["Preview - btn txt"]='Просмотр';//Текст кнопки "Просмотр" - открывает файл для просмотра
$uInt_uEditor_setup_article["Delete - btn txt"]='Удалить';//Текст кнопки "Удалить" - удаляет файл
$uInt_uEditor_setup_article["Delete all - btn txt"]='Удалить все';//Текст кнопки "Удалить все" - удаляет всме файлы, прикрепленные к статье
$uInt_uEditor_setup_article["Art title - dg title"]='Заголовок текста';//Заголовок диалога с редактором заголовка статьи
$uInt_uEditor_setup_article["Title - input label"]='Заголовок:';//Подпись к полю "Заголовок"
$uInt_uEditor_setup_article["Show title on page - input label"]='Отображать заголовок на странице';//Подпись к полю "Отображать заголовок на странице"
$uInt_uEditor_setup_article["Art url - dg title"]='URL текста';//Заголовок диалога с редактором URL страницы
$uInt_uEditor_setup_article["Basic url - input label"]='Основной URL:';//Подпись к полю "Основной URL"
$uInt_uEditor_setup_article["Beautiful url - input label"]='Красивый URL:';//Подпись к полю "Красивый URL"
$uInt_uEditor_setup_article["Beautiful url - descr"]='Вы можете изменить основной URL (адрес страницы) или задать Красивый URL чтобы вместо, например mysite.com/page/stranitsa50 получить mysite.com/mypage.html.';//Описание к полю "Красивый URL"
$uInt_uEditor_setup_article["Article access - dg title"]='Доступ к тексту';//Заголовок диалога с редактором доступа к статье
$uInt_uEditor_setup_article["Access - input label"]='Доступ:';//Подпись к полю "Доступ"
$uInt_uEditor_setup_article["Access - descr"]='Вы можете выбрать доступ - только пользователи, обладающие таким доступом смогут просматривать эту страницу';//Описание к полю "Доступ"
$uInt_uEditor_setup_article["Menu binding - dg title"]='Привязка к меню';//Заголовок диалога с редактором привязки статьи к пунктам меню
$uInt_uEditor_setup_article["Open menu - input label"]='Открыть меню:';//Подпись к полю "Открыть меню"
$uInt_uEditor_setup_article["Menu binding descr"]='Вы можете выбрать пункт меню, который будет активным при открытии этой страницы.';//Описание к полю "Открыть меню"
$uInt_uEditor_setup_article["Page date - dg title"]='Дата и время текста';//Заголовок диалога с редактором даты статьи
$uInt_uEditor_setup_article["Date - input label"]='Дата:';//Подпись к полю "Дата"
$uInt_uEditor_setup_article["Time - input label"]='Время:';//Подпись к полю "Время"
$uInt_uEditor_setup_article["Show date and time - input label"]='Показывать дату и время на странице';//Подпись к полю "Показывать дату и время на странице"
$uInt_uEditor_setup_article["Date and time - descr"]='Вы можете установить дату и время для вашей страницы и отобразить его в конце текста.<br>Также дата и время может отображаться в различных виджетах, например в списке новостей на главной странице.';//Описания для даты и времени на странице статьи
$uInt_uEditor_setup_article["meta-description - input label"]='Описание (мета-тег description)';//Подпись к полю "Описание (мета-тег description)"
$uInt_uEditor_setup_article["meta-keywords - input label"]='Ключевые слова (мета-теш keywords)';//Подпись к полю "Ключевые слова (мета-теш keywords)"
$uInt_uEditor_setup_article["meta-tags description"]='Для поисковой оптимизации Вы можете задать значения мета-тегов keywords и description';//Описание мета-тегов SEO
$uInt_uEditor_setup_article["Rubrics - dg title"]='Рубрики';//Заголовок диалога со списком рубрик для статьи
$uInt_uEditor_setup_article["Attached rubrics - list title"]='Прикрепленные рубрики';//Заголовок списка прикрепленных рубрик в диалоге со списком рубрик для прикрепления к статье
$uInt_uEditor_setup_article["Unattached rubrics - list title"]='Неприкрепленные рубрики';//Заголовок списка неприкрепленных рубрик в диалоге со списком рубрик для прикрепления к статье
$uInt_uEditor_setup_article["Create rubric - btn txt"]='Создать рубрику';//Текст кнопки "Создать рубрику" в диалоге со списком рубрик для прикрепления
$uInt_uEditor_setup_article["Rubric editor - dg title"]='Редактор рубрики';//Заголовок диалога с редактором рубрики
$uInt_uEditor_setup_article["Rubric title - input label"]='Название рубрики';//Подпись к полю "Название рубрики"
$uInt_uEditor_setup_article["Delete rubric - dg title"]='Удалить рубрику?';//Заголовок диалога с подтверждением удаления рубрики
$uInt_uEditor_setup_article["Delete rubric - confirmation text"]='Вы действительно хотите удалить рубрику?';//Текст диалога с подтверждением удаления рубрики
$uInt_uEditor_setup_article["Delete rubric - btn txt"]='Удалить';//Кнопка подтверждения удаления рубрики
$uInt_uEditor_setup_article["HTML-blocks - dg title"]='Вставки';//Заголовок диалога с редактором вставок на страницу
$uInt_uEditor_setup_article["Attached html-blocks - list title"]='Прикрепленные вставки';//Заголовок списка с прикрепленными вставками
$uInt_uEditor_setup_article["Unattached html-blocks - list title"]='Неприкрепленные вставки';//Заголовок списка с неприкрепленными вставками
$uInt_uEditor_setup_article["Create html-block - btn txt"]='Создать вставку';//Кнопка для открытия диалога создания новой вставки
$uInt_uEditor_setup_article["Delete html-block - dg title"]='Удалить вставку?';//Заголовок диалога с подтверждением удаления вставки
$uInt_uEditor_setup_article["Delete html-block - confirmation text"]='Вы действительно хотите удалить вставку?';//Текст диалога с подтверждением удаления вставки
$uInt_uEditor_setup_article["Delete html-block - btn txt"]='Удалить';//Кнопка удаления вставки диалога с подтверждением удаления вставки
$uInt_uEditor_setup_article["Html-block editor - dg title"]='Редактор Вставки';//Заголовок диалога с редактором вставки
$uInt_uEditor_setup_article["Delete art - dg title"]='Удалить текст?';//Заголовок диалога с подтверждением удаления статьи
$uInt_uEditor_setup_article["Delete art - confirmation text"]='Страница и ВСЕ прикрепленные к ней файлы будут удалены безвозвратно!<br>Если на страницу или на прикрепленные к ней файлы есть ссылки, то они перестанут работать';//Текст диалога с подтверждением удаления статьи
$uInt_uEditor_setup_article["Delete art - confirm btn txt"]='Да, удаляем';//Кнопка подтверждения удаления в диалоге с подтверждением удаления статьи
$uInt_uEditor_setup_article["Access 0"]='Все пользователи';//Название прав доступа к статье. Все пользователи
$uInt_uEditor_setup_article["Access 2"]='Только авторизованные';//Название прав доступа к статье. Только авторизованные
$uInt_uEditor_setup_article["Access 11"]='Только неавторизованные';//Название прав доступа к статье. Только неавторизованные
$uInt_uEditor_setup_article["Article - folder title"]='Текст ';//Название папки по умолчанию на диске для статьи
$uInt_uEditor_setup_article["Current text id - label"]='ID этого текста:';//Подпись к полю с ID открытого текста