<?php
$uInt_uPage_admin_new_page["Text on top"]='(Текст сверху)';//Название текста на странице. Этот текст создается автоматически.(Text on top)
$uInt_uPage_admin_new_page["row 2. text in left col"]='(Ряд 2. Текст в левой колонке)';//Название текста на странице. Этот текст создается автоматически.(Row 2. Text in left column)
$uInt_uPage_admin_new_page["row 2. img in right col"]='(Ряд 2. Изображение в правой колонке)';//Название текста на странице. Этот текст создается автоматически.(Row 2. Image in right column)
$uInt_uPage_admin_new_page["row 4. img in left col"]='(Ряд 4. Изображение в левой колонке)';//Название текста на странице. Этот текст создается автоматически.(Row 4. Image in left column)
$uInt_uPage_admin_new_page["row 4. text in right col"]='(Ряд 4. Текст в правой колонке)';//Название текста на странице. Этот текст создается автоматически.(Row 4. Text in right column)
$uInt_uPage_admin_new_page["row 2. text"]='(Ряд 2. Текст)';//Название текста на странице. Этот текст создается автоматически.(Row 2. Text)
$uInt_uPage_admin_new_page["row 4. img in right col"]='(Ряд 4. Изображение в правой колонке)';//Название текста на странице. Этот текст создается автоматически.(Row 4. Image in right column)
$uInt_uPage_admin_new_page["row 1. img in left col"]='(Ряд 1. Изображение в левой колонке)';//Название текста на странице. Этот текст создается автоматически.(Row 1. Image in left column)
$uInt_uPage_admin_new_page["row 1. img in right col"]='(Ряд 1. Изображение в правой колонке)';//Название текста на странице. Этот текст создается автоматически.(Row 1. Image in right column)
$uInt_uPage_admin_new_page["row 2. title and subtitle"]='(Ряд 2. Заголовок и подзаголовок)';//Название текста на странице. Этот текст создается автоматически.(Row 2. Title and subtitle)
$uInt_uPage_admin_new_page["row 3. text"]='(Ряд 3. Текст)';//Название текста на странице. Этот текст создается автоматически.(Row 3. Text)
$uInt_uPage_admin_new_page["row 1. text in left col"]='(Ряд 1. Текст в левой колонке)';//Название текста на странице. Этот текст создается автоматически.(Row 1. Text in left column)
$uInt_uPage_admin_new_page["form of page number"]='Форма страницы #';//Название текста на странице. Этот текст создается автоматически.Form of page #
$uInt_uPage_admin_new_page["form field Name"]='Имя';//Название поля в форме, созданной по шаблону страницыName
$uInt_uPage_admin_new_page["form field Name placeholder"]='Иван';//Название поля в форме, созданной по шаблону страницыJohn
$uInt_uPage_admin_new_page["form field Last Name"]='Фамилия';//Название поля в форме, созданной по шаблону страницыLast name
$uInt_uPage_admin_new_page["form field Last Name placeholder"]='Иванов';//Название поля в форме, созданной по шаблону страницыJohnson
$uInt_uPage_admin_new_page["form field Email"]='E-mail';//Название поля в форме, созданной по шаблону страницыE-mail
$uInt_uPage_admin_new_page["form field Phone"]='Телефон';//Название поля в форме, созданной по шаблону страницыPhone
$uInt_uPage_admin_new_page["form field Message"]='Сообщение';//Название поля в форме, созданной по шаблону страницыMessage
$uInt_uPage_admin_new_page["form field Message placeholder"]='Ваше сообщение здесь';//Название поля в форме, созданной по шаблону страницыYour message here