<?php
$uInt_uEvents_events["Today"]='Сегодня';//Кнопка "Сегодня" - обозначение сегодняшней даты для календаря на странице просмотра типа события
$uInt_uEvents_events["Add title"]='Добавить заголовок';//Кнопка "Добавить заголовок" для правого меню (режимредактирования)
$uInt_uEvents_events["Move or rename this element"]='Переместить или переименовать этот элемент';//Заголовок кнопки-иконки напротив каждого пункта меню (режим редактирования)
$uInt_uEvents_events["Change the name of the event type"]='Изменить название типа событий';//Заголовок кнопки-иконки "Изменить название" (иконка с карандашем)
$uInt_uEvents_events["Change the URL type of event"]='Изменить URL типа событий';//Заголовок кнопки-иконки "Изменить URL" (иконка с надписью "URL")
$uInt_uEvents_events["Delete event type"]='Удалить тип событий';//Заголовок кнопки-иконки "Удалить тип события" (иконка с крестиком)
$uInt_uEvents_events["Type title editor - dg title"]='Редактор названия типа событий';//Заголовок диалога с редактором названия типа событий
$uInt_uEvents_events["Event type title - input label"]='Введите новое название';//Подпись к полю "Название типа события" в диалоге редактора названия типа событий
$uInt_uEvents_events["Close - btn txt"]='Закрыть';//Кнопка "Закрыть" в диалогах
$uInt_uEvents_events["Save - btn txt"]='Сохранить';//Кнопка "Сохранить" в диалогах
$uInt_uEvents_events["URL of event type editor - dg title"]='Редактор URL типа событий';//Заголовок диалога с редактором URL типа событий
$uInt_uEvents_events["URL - input label"]='Введите новый URL';//Подпись к полю "URL" в диалоге редактора URL типа событий
$uInt_uEvents_events["Files - dg title"]='Файлы';//Заголовок диалога со списком файлов типа событий
$uInt_uEvents_events["Watch - btn txt"]='Просмотр';//Текст кнопки "Просмотр" в списке файлов
$uInt_uEvents_events["Insert - btn txt"]='Вставить';//Текст кнопки "Вставить" в списке файлов
$uInt_uEvents_events["Delete - btn txt"]='Удалить';//Текст кнопки "Удалить" в списке файлов
$uInt_uEvents_events["Delete All - btn txt"]='Удалить Все';//Текст кнопки "Удалить Все" в списке файлов
$uInt_uEvents_events["Delete event type - dg title"]='Удалить тип событий?';//Заголовок диалога подтверждения удаления типа событий
$uInt_uEvents_events["Cancel - btn txt"]='Отмена';//Текст кнопки "Отмена" в диалогах
$uInt_uEvents_events["Delete and move events - btn txt"]='Удалить и перенести события';//Текст кнопки "Удалить и перенести события" в диалоге удаления типа событий. При клике на нее тип событий будет удален, а события перенесены в другое событие
$uInt_uEvents_events["Delete event type and events attached - btn txt"]='Удалить вместе с событиями';//Текст кнопки "Удалить вместе с событиями" в диалоге удаления типа событий. При клике на нее тип событий будет удален вместе со свсеми прикрепленными событиями
$uInt_uEvents_events["Event type dates - header"]='даты';//Заголовок списка дат на странице календаря событий