<?php
$uInt_uEditor_setup_article["Close - btn txt"]='Close';//Кнопка "Закрыть" в диалоге
$uInt_uEditor_setup_article["Save - btn txt"]='Save';//Кнопка "Сохранить" в диалоге
$uInt_uEditor_setup_article["Basic page image - dg title"]='Primary image';//Заголовок диалога загрузчика основной картинки статьи
$uInt_uEditor_setup_article["Show image on current page - input label"]='Show primary image on current page';//Подпись к полю "Отображать изображение на этой странице?"
$uInt_uEditor_setup_article["Show image on current page - input descr"]='If not checked: primary image is hidden on current page';//Описание к полю "Отображать изображение на этой странице?"
$uInt_uEditor_setup_article["Show image on pages - input label"]='Show primary image on pages by default';//Подпись к полю "Отображать изображения страниц на страницах статей?"
$uInt_uEditor_setup_article["Show image on pages - input descr"]='If not checked: primary image is hidden on every page by default';//Описание к полю "Отображать изображения страниц на страницах статей?"
$uInt_uEditor_setup_article["Basic image width on page - input label"]='Primary image width on current page';//Подпись к полю "Ширина изображения на этой странице"
$uInt_uEditor_setup_article["Basic image width on articles list - input label"]='Primary image width in texts list of section (example: News)';//Подпись к полю "Ширина изображения в списке страниц в рубрике (например список всех новостей)"
$uInt_uEditor_setup_article["Basic image width in widget - input label"]='Primary image width in widgets (example: news in sidebar)';//Подпись к полю "Ширина изображения в виджете рубрики (например новости на главной)"
$uInt_uEditor_setup_article["Basic image description"]='Primary image is shown in widgets. For example in news.';//Описание основного изобрежения статьи
$uInt_uEditor_setup_article["Delete image - btn txt"]='Delete image';//Кнопка "Удалить изображение" в диалоге редактора основного изображения статьи
$uInt_uEditor_setup_article["Short text - dg title"]='Short text';//Заголовок диалога с редактором краткого текста страницы
$uInt_uEditor_setup_article["short text - input label"]='Short text: ';//Подпись к полю "Краткий текст:"
$uInt_uEditor_setup_article["Short text - description"]='Short text is shown in widgets. For example in news';//Описание к полю "Краткий текст:"
$uInt_uEditor_setup_article["Uploaded files - dg title"]='Uploaded files';//Заголовок диалога со списком файлов, загруженных к статье
$uInt_uEditor_setup_article["Insert to editor - btn txt"]='Insert to editor';//Текст кнопки "Вставить в редактор" - вставляет файл в редактор
$uInt_uEditor_setup_article["Preview - btn txt"]='View';//Текст кнопки "Просмотр" - открывает файл для просмотра
$uInt_uEditor_setup_article["Delete - btn txt"]='Delete';//Текст кнопки "Удалить" - удаляет файл
$uInt_uEditor_setup_article["Delete all - btn txt"]='Delete all';//Текст кнопки "Удалить все" - удаляет всме файлы, прикрепленные к статье
$uInt_uEditor_setup_article["Art title - dg title"]='Text title';//Заголовок диалога с редактором заголовка статьи
$uInt_uEditor_setup_article["Title - input label"]='Title: ';//Подпись к полю "Заголовок"
$uInt_uEditor_setup_article["Show title on page - input label"]='Show text title on current page';//Подпись к полю "Отображать заголовок на странице"
$uInt_uEditor_setup_article["Art url - dg title"]='Text URL';//Заголовок диалога с редактором URL страницы
$uInt_uEditor_setup_article["Basic url - input label"]='Basic url: ';//Подпись к полю "Основной URL"
$uInt_uEditor_setup_article["Beautiful url - input label"]='Simple url:';//Подпись к полю "Красивый URL"
$uInt_uEditor_setup_article["Beautiful url - descr"]='You can change basic URL (page address) or set simply url to make page address appear as "mysite.com/mypage.html" instead of "mysite.com/page/page50" ';//Описание к полю "Красивый URL"
$uInt_uEditor_setup_article["Article access - dg title"]='Text access';//Заголовок диалога с редактором доступа к статье
$uInt_uEditor_setup_article["Access - input label"]='Access: ';//Подпись к полю "Доступ"
$uInt_uEditor_setup_article["Access - descr"]='You can set access rule for page: only users with sufficient rights would be able to open this page';//Описание к полю "Доступ"
$uInt_uEditor_setup_article["Menu binding - dg title"]='Menu assignment';//Заголовок диалога с редактором привязки статьи к пунктам меню
$uInt_uEditor_setup_article["Open menu - input label"]='Open menu: ';//Подпись к полю "Открыть меню"
$uInt_uEditor_setup_article["Menu binding descr"]='You can choose a menu item that will be active on this page';//Описание к полю "Открыть меню"
$uInt_uEditor_setup_article["Page date - dg title"]='Text date and time';//Заголовок диалога с редактором даты статьи
$uInt_uEditor_setup_article["Date - input label"]='Date: ';//Подпись к полю "Дата"
$uInt_uEditor_setup_article["Time - input label"]='Time: ';//Подпись к полю "Время"
$uInt_uEditor_setup_article["Show date and time - input label"]='Show date and time on current page';//Подпись к полю "Показывать дату и время на странице"
$uInt_uEditor_setup_article["Date and time - descr"]='You can set date and time for this page and show it at the bottom of page.<br>Date and time is also shown in widgets, for example News';//Описания для даты и времени на странице статьи
$uInt_uEditor_setup_article["meta-description - input label"]='Description (meta-tag)';//Подпись к полю "Описание (мета-тег description)"
$uInt_uEditor_setup_article["meta-keywords - input label"]='Keywords (meta-tag)';//Подпись к полю "Ключевые слова (мета-теш keywords)"
$uInt_uEditor_setup_article["meta-tags description"]='You can define description and keywords for SEO';//Описание мета-тегов SEO
$uInt_uEditor_setup_article["Rubrics - dg title"]='Sections';//Заголовок диалога со списком рубрик для статьи
$uInt_uEditor_setup_article["Attached rubrics - list title"]='Attached sections';//Заголовок списка прикрепленных рубрик в диалоге со списком рубрик для прикрепления к статье
$uInt_uEditor_setup_article["Unattached rubrics - list title"]='Unattached sections';//Заголовок списка неприкрепленных рубрик в диалоге со списком рубрик для прикрепления к статье
$uInt_uEditor_setup_article["Create rubric - btn txt"]='Create section';//Текст кнопки "Создать рубрику" в диалоге со списком рубрик для прикрепления
$uInt_uEditor_setup_article["Rubric editor - dg title"]='Section editor';//Заголовок диалога с редактором рубрики
$uInt_uEditor_setup_article["Rubric title - input label"]='Section title';//Подпись к полю "Название рубрики"
$uInt_uEditor_setup_article["Delete rubric - dg title"]='Delete section?';//Заголовок диалога с подтверждением удаления рубрики
$uInt_uEditor_setup_article["Delete rubric - confirmation text"]='Are you sure you want to delete section?';//Текст диалога с подтверждением удаления рубрики
$uInt_uEditor_setup_article["Delete rubric - btn txt"]='Delete';//Кнопка подтверждения удаления рубрики
$uInt_uEditor_setup_article["HTML-blocks - dg title"]='HTML-boxes';//Заголовок диалога с редактором вставок на страницу
$uInt_uEditor_setup_article["Attached html-blocks - list title"]='Attached boxes';//Заголовок списка с прикрепленными вставками
$uInt_uEditor_setup_article["Unattached html-blocks - list title"]='Unattached boxes';//Заголовок списка с неприкрепленными вставками
$uInt_uEditor_setup_article["Create html-block - btn txt"]='Create html-box';//Кнопка для открытия диалога создания новой вставки
$uInt_uEditor_setup_article["Delete html-block - dg title"]='Delete box?';//Заголовок диалога с подтверждением удаления вставки
$uInt_uEditor_setup_article["Delete html-block - confirmation text"]='Are you sure you want to delete box?';//Текст диалога с подтверждением удаления вставки
$uInt_uEditor_setup_article["Delete html-block - btn txt"]='Delete';//Кнопка удаления вставки диалога с подтверждением удаления вставки
$uInt_uEditor_setup_article["Html-block editor - dg title"]='Html-box editor';//Заголовок диалога с редактором вставки
$uInt_uEditor_setup_article["Delete art - dg title"]='Delete text?';//Заголовок диалога с подтверждением удаления статьи
$uInt_uEditor_setup_article["Delete art - confirmation text"]="Text and all attached files will be deleted and couldn't be restored<br>All links to this page will be broken";//Текст диалога с подтверждением удаления статьи
$uInt_uEditor_setup_article["Delete art - confirm btn txt"]='Delete';//Кнопка подтверждения удаления в диалоге с подтверждением удаления статьи
$uInt_uEditor_setup_article["Access 0"]='All users';//Название прав доступа к статье. Все пользователи
$uInt_uEditor_setup_article["Access 2"]='Authorized only';//Название прав доступа к статье. Только авторизованные
$uInt_uEditor_setup_article["Access 11"]='Unauthorized only';//Название прав доступа к статье. Только неавторизованные
$uInt_uEditor_setup_article["Article - folder title"]='Text ';//Название папки по умолчанию на диске для статьи
$uInt_uEditor_setup_article["Current text id - label"]='Current text id: ';//Подпись к полю с ID открытого текста