<?php
$uInt_uForms_admin_form_editor["Notification email block header"]='Сообщение, отправляемое на почту<br><small>На почту отправителя можно отправить сообщение после того, как он заполнит форму</small>';//Заголовок блока "Сообщение, отправляемое на почту после заполнения формы"
$uInt_uForms_admin_form_editor["Emails to send notification - field label"]='На какие email отправлять?';//Подпись к списку email для выбора поля, в которое пользователь заполняет свой email - на это поле будет отправляться письмо
$uInt_uForms_admin_form_editor["Email to send notification - descr"]='В форме должны быть поля с разрешенными значениями <b>Email</b> - они отображаются здесь.';//Описание списка полей email для отправки письма после того, как пользователь заполнит форму
$uInt_uForms_admin_form_editor["Email subject - input label"]='Тема email сообщения';//Подпись к полю "Тема email сообщения"
$uInt_uForms_admin_form_editor["Email subject - input placeholder"]='Тема сообщения email';//Placeholder к полю "Тема email сообщения"
$uInt_uForms_admin_form_editor["Save subject - btn txt"]='Сохранить тему сообщения';//Кнопка "Сохранить тему сообщения"
$uInt_uForms_admin_form_editor["Subject - descr"]='Если тема или текст не заполнены, то сообщение не будет отправляться!';//Описание того, как работает тема сообщения
$uInt_uForms_admin_form_editor["Email text - input label"]='Текст сообщения';//Подпись к полю "Текст сообщения"
$uInt_uForms_admin_form_editor["Email text - descr"]='Все ссылки здесь должны быть абсолютными, то есть начинаться с http://сайт.com. Если будут относительные, то в письме они будут битыми.';//Подсказка по заполнению контента сообщения
$uInt_uForms_admin_form_editor["Row editor - dg title"]='Редактор ряда';//Заголовок Диалога "Редактор ряда"
$uInt_uForms_admin_form_editor["Col editor - dg title"]='Редактор колонки';//Заголовок диалога "редактор колонки"
$uInt_uForms_admin_form_editor["Block deletion - dg title"]='Удаление блока';//Заголовок диалога "Удаление блока" - подтверждение удаления
$uInt_uForms_admin_form_editor["Block deletion confirm - txt"]='Вы действительно хотите удалить этот блок?<br>Все колонки и поля, прикрепленные к этому блоку, будут удалены.';//Текст диалога "Удаление блока" - подтверждение удаления
$uInt_uForms_admin_form_editor["Col deletion - dg title"]='Удаление колонки';//Заголовок диалога-подтверждение "Удаление колонки"
$uInt_uForms_admin_form_editor["Col deletion - confirm"]='Вы действительно хотите удалить эту колонку?<br>Все поля, прикрепленные к этой колонке, будут удалены.';//Текст диалога-подтверждения "Удаление колонки"
$uInt_uForms_admin_form_editor["Field deletion - dg title"]='Удаление поля';//Заголовок диалога-подтверждения "Удаление поля"
$uInt_uForms_admin_form_editor["Field deletion - confirm"]='Вы действительно хотите удалить это поле?';//Текст диалога-подтверждения "Удаление поля"
$uInt_uForms_admin_form_editor["Field editor - dg title"]='Редактор поля';//Заголовок диалога с редактором поля формы
$uInt_uForms_admin_form_editor["Save - btn txt"]='Сохранить';//Кнопка "сохранить" в диалогах
$uInt_uForms_admin_form_editor["Delete field - btn"]='Удалить поле';//Кнопка "Удалить поле"
$uInt_uForms_admin_form_editor["Field values - dg title"]='Значения поля';//Заголовок диалога с редактором значений поля
$uInt_uForms_admin_form_editor["Add field value - btn"]='Добавить значение';//Кнопка "Добавит значение поля"
$uInt_uForms_admin_form_editor["Done - btn"]='Готово';//Кнопка "Готово"
$uInt_uForms_admin_form_editor["Field value editor - dg title"]='Редактор значения';//Заголовок диалога редактора значения
$uInt_uForms_admin_form_editor["Save - btn"]='Сохранить';//Кнопка "Сохранить"
$uInt_uForms_admin_form_editor["Delete field value - btn"]='Удалить значение';//Кнопка "Удалить значение поля"
$uInt_uForms_admin_form_editor["Delete field value - dg title"]='Удалить значение?';//Заголовок диалога "Удалить значение"
$uInt_uForms_admin_form_editor["Are you're sure about deleting this field value - msg"]='Вы действительно хотите удалить это значение?';//Подтверждение "Удалить значение"
$uInt_uForms_admin_form_editor["Cancel - btn"]='Отмена';//Кнопка "Отмена"
$uInt_uForms_admin_form_editor["Delete - btn"]='Удалить';//Кнопка "Удалить"
$uInt_uForms_admin_form_editor["Form settings - dg title"]='Настройка формы';//Диалог с настройками формы
$uInt_uForms_admin_form_editor["Form title - label"]='Заголовок формы';//Подпись к полю "Заголовок формы"
$uInt_uForms_admin_form_editor["Form descr - label"]='Описание';//Подпись к полю "Описание"
$uInt_uForms_admin_form_editor["Form result email - label"]='Сообщение об успешной отправке формы';//Подпись к полю "Сообщение об успешной отправке формы"
$uInt_uForms_admin_form_editor["Form result email - hint"]='Какой текст отображать посетителю, когда он успешно отправит форму? Не больше 255 символов.';//Подсказка к полю "Сообщение об успешной отправке формы"
$uInt_uForms_admin_form_editor["Close - btn"]='Закрыть';//Кнопка "Закрыть"
$uInt_uForms_admin_form_editor["Uploaded files - dg title"]='Загруженные файлы';//Заголовок диалога "Загруженный файлы"
$uInt_uForms_admin_form_editor["Insert file to editor - btn"]='Вставить в редактор';//Кнопка "Вставить в редактор" в диалоге со списком файлов
$uInt_uForms_admin_form_editor["View files - btn"]='Просмотр файлов';//Кнопка "Просмотр файлов" в диалоге со списком файлов
$uInt_uForms_admin_form_editor["Delete files - btn"]='Удаление файлов';//Кнопка "Удаление файлов" в диалоге со списком файлов
$uInt_uForms_admin_form_editor["Delete all files - btn"]='Удалить все';//Кнопка "Удалить все" в диалоге со списком файлов
$uInt_uForms_admin_form_editor["Page name"]='Конструктор формы';//Название страницы
$uInt_uForms_admin_form_editor["Submit btn txt"]='Текст кнопки "Отправить"';//Текст, который отображается на кнопке «Отправить форму»
