<?php
$uInt_uForms_admin_form_editor["Notification email block header"]='Message text<br><small>You can send email to user after he submits this form</small>';//Заголовок блока "Сообщение, отправляемое на почту после заполнения формы"
$uInt_uForms_admin_form_editor["Emails to send notification - field label"]='The list of emails to send messages to?';//Подпись к списку email для выбора поля, в которое пользователь заполняет свой email - на это поле будет отправляться письмо
$uInt_uForms_admin_form_editor["Email to send notification - descr"]='Form should contain fields of type "Email". They are shown here';//Описание списка полей email для отправки письма после того, как пользователь заполнит форму
$uInt_uForms_admin_form_editor["Email subject - input label"]='Email subject';//Подпись к полю "Тема email сообщения"
$uInt_uForms_admin_form_editor["Email subject - input placeholder"]='Email subject';//Placeholder к полю "Тема email сообщения"
$uInt_uForms_admin_form_editor["Save subject - btn txt"]='Save subject';//Кнопка "Сохранить тему сообщения"
$uInt_uForms_admin_form_editor["Subject - descr"]='If either subject or text is empty - email won’t be sent';//Описание того, как работает тема сообщения
$uInt_uForms_admin_form_editor["Email text - input label"]='Email text';//Подпись к полю "Текст сообщения"
$uInt_uForms_admin_form_editor["Email text - descr"]='All links here should be absolute: they must begin from http://mysite.com. All relative links will be broken';//Подсказка по заполнению контента сообщения
$uInt_uForms_admin_form_editor["Row editor - dg title"]='Row editor';//Заголовок Диалога "Редактор ряда"
$uInt_uForms_admin_form_editor["Col editor - dg title"]='Column editor';//Заголовок диалога "редактор колонки"
$uInt_uForms_admin_form_editor["Block deletion - dg title"]='Delete row';//Заголовок диалога "Удаление блока" - подтверждение удаления
$uInt_uForms_admin_form_editor["Block deletion confirm - txt"]='Are you sure you want to delete this row?<br>All columns and fields attached will be permanently lost';//Текст диалога "Удаление блока" - подтверждение удаления
$uInt_uForms_admin_form_editor["Col deletion - dg title"]='Delete column';//Заголовок диалога-подтверждение "Удаление колонки"
$uInt_uForms_admin_form_editor["Col deletion - confirm"]='Are you sure you want to delete this column?<br>All fields attached will be permanently lost';//Текст диалога-подтверждения "Удаление колонки"
$uInt_uForms_admin_form_editor["Field deletion - dg title"]='Delete field';//Заголовок диалога-подтверждения "Удаление поля"
$uInt_uForms_admin_form_editor["Field deletion - confirm"]='Are you sure you want to delete this field?';//Текст диалога-подтверждения "Удаление поля"
$uInt_uForms_admin_form_editor["Field editor - dg title"]='Field editor';//Заголовок диалога с редактором поля формы
$uInt_uForms_admin_form_editor["Save - btn txt"]='Save';//Кнопка "сохранить" в диалогах
$uInt_uForms_admin_form_editor["Delete field - btn"]='Delete field';//Кнопка "Удалить поле"
$uInt_uForms_admin_form_editor["Field values - dg title"]='Field values';//Заголовок диалога с редактором значений поля
$uInt_uForms_admin_form_editor["Add field value - btn"]='Add value';//Кнопка "Добавит значение поля"
$uInt_uForms_admin_form_editor["Done - btn"]='Done';//Кнопка "Готово"
$uInt_uForms_admin_form_editor["Field value editor - dg title"]='Value editor';//Заголовок диалога редактора значения
$uInt_uForms_admin_form_editor["Save - btn"]='Save';//Кнопка "Сохранить"
$uInt_uForms_admin_form_editor["Delete field value - btn"]='Delete value';//Кнопка "Удалить значение поля"
$uInt_uForms_admin_form_editor["Delete field value - dg title"]='Delete value?';//Заголовок диалога "Удалить значение"
$uInt_uForms_admin_form_editor["Are you're sure about deleting this field value - msg"]='Are you sure you want to delete this value?';//Подтверждение "Удалить значение"
$uInt_uForms_admin_form_editor["Cancel - btn"]='Cancel';//Кнопка "Отмена"
$uInt_uForms_admin_form_editor["Delete - btn"]='Delete';//Кнопка "Удалить"
$uInt_uForms_admin_form_editor["Form settings - dg title"]='Form settings';//Диалог с настройками формы
$uInt_uForms_admin_form_editor["Form title - label"]='Form title';//Подпись к полю "Заголовок формы"
$uInt_uForms_admin_form_editor["Form descr - label"]='Description';//Подпись к полю "Описание"
$uInt_uForms_admin_form_editor["Form result email - label"]='Notification text after form has been submitted successfully';//Подпись к полю "Сообщение об успешной отправке формы"
$uInt_uForms_admin_form_editor["Form result email - hint"]='What message we should show user after he has submitted this form? Over 255 letters.';//Подсказка к полю "Сообщение об успешной отправке формы"
$uInt_uForms_admin_form_editor["Close - btn"]='Close';//Кнопка "Закрыть"
$uInt_uForms_admin_form_editor["Uploaded files - dg title"]='Uploaded files';//Заголовок диалога "Загруженный файлы"
$uInt_uForms_admin_form_editor["Insert file to editor - btn"]='Insert to editor';//Кнопка "Вставить в редактор" в диалоге со списком файлов
$uInt_uForms_admin_form_editor["View files - btn"]='View files';//Кнопка "Просмотр файлов" в диалоге со списком файлов
$uInt_uForms_admin_form_editor["Delete files - btn"]='Delete files';//Кнопка "Удаление файлов" в диалоге со списком файлов
$uInt_uForms_admin_form_editor["Delete all files - btn"]='Delete all';//Кнопка "Удалить все" в диалоге со списком файлов
$uInt_uForms_admin_form_editor["Page name"]='Form construcor';//Название страницы
$uInt_uForms_admin_form_editor["Submit btn txt"]='Submit button text';//Текст, который отображается на кнопке «Отправить форму»
