<?php
$uInt_uEvents_event["Start date"]='Start date';//Таблица. Информации о дате события
$uInt_uEvents_event["Duration, days"]='Duration, days';//Таблица. Информации о дате события
$uInt_uEvents_event["Delete date"]='Delete this date';//Заголовок Кнопки "Удалить эту дату"
$uInt_uEvents_event["Change date"]='Edit this date';//Заголовок Кнопки "Изменить дату"
$uInt_uEvents_event["Where to set up this button?"]='Where can I edit this button?';//Заголовок диалогового окошка, которое открывается при нажатии на иконку со знаком вопроса в блоке "Есть вопросы" (режим редактирования)
$uInt_uEvents_event["Have questions?"]='Questions?';//Заголовок блока
$uInt_uEvents_event["Contact us!"]='Call us!';//Кнопка "Свяжитесь с нами"
$uInt_uEvents_event["New event title - dg title"]='Enter new title for event';//Заголовок диалога изменения названия события
$uInt_uEvents_event["Close - btn txt"]='Close';//Кнопка "Закрыть" в диалогах
$uInt_uEvents_event["Save - btn txt"]='Save';//Кнопка "Сохранить" в диалогах
$uInt_uEvents_event["Choose event type - dg title"]='Choose a new event type';//Заголовок диалога со сменой типа события
$uInt_uEvents_event["Files - dg title"]='Files';//Заголовок диалога со списком файлов события
$uInt_uEvents_event["Watch - btn txt"]='View';//Текст кнопки "Просмотр" в списке файлов
$uInt_uEvents_event["Insert - btn txt"]='Insert';//Текст кнопки "Вставить" в списке файлов
$uInt_uEvents_event["Delete - btn txt"]='Delete';//Текст кнопки "Удалить" в списке файлов
$uInt_uEvents_event["Delete All - btn txt"]='Delete all';//Текст кнопки "Удалить Все" в списке файлов
$uInt_uEvents_event["Add date - dg title"]='Add date';//Заголовок диалога с добавлением даты события
$uInt_uEvents_event["Date - input label"]='Date';//Подпись к полю "Дата" в диалоге добавления даты события
$uInt_uEvents_event["Duration - input label"]='Duration';//Подпись к полю "Продолжительность" в диалоге добавления даты события
$uInt_uEvents_event["Duration - input dimension"]='days';//Размерность к полю "Продолжительность" в диалоге добавления даты события. Например, 15 "дней"
$uInt_uEvents_event["Comment - input label"]='Comment';//Подпись к полю "Комментарий" в диалоге добавления даты события
$uInt_uEvents_event["Add - btn txt"]='Add';//Текст кнопки "Добавить" в диалогах
$uInt_uEvents_event["Assign form - dg title"]='Assign form';//Заголовок диалога "Назначить форму"
$uInt_uEvents_event["Assign code - dg title"]='Assign code';//Заголовок диалога "Назначить код"
$uInt_uEvents_event["Code to assign - input label"]='Code to assign';//Подпись к полю "Код для вставки" в диалоге прикрепления кода к событию
$uInt_uEvents_event["Datepicker lang"]='en-GB';//Язык Datepicker
$uInt_uEvents_event["Select date btn"]='Select';//Кнопка выбора даты события
$uInt_uEvents_event["Event page url editor - dg name"]='Event page url editor';//	Название диалога с редактором URL страницы
$uInt_uEvents_event["Fill the page url - label"]='Fill the page url';//	Подпись к полю, в которое нужно ввести URL страницы
$uInt_uEvents_event["Event show dates - dg name"]='Event show dates';//	Название диалога, в котором задаются даты показа события - в пределах этих дат событие будет отображаться на сайте, а потом будет скрыто
$uInt_uEvents_event["Event show dates - beginning - label"]='Beginning';//	Подпись к выбору даты начала показа события в диалоге, в котором задаются даты показа события - в пределах этих дат событие будет отображаться на сайте, а потом будет скрыто
$uInt_uEvents_event["Event show dates - end - label"]='End';//	Подпись к выбору даты окончания показа события в диалоге, в котором задаются даты показа события - в пределах этих дат событие будет отображаться на сайте, а потом будет скрыто