<?php
$uInt_processors_acl_name["acl_name_1"]='View site content';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_2"]='Authorized user features';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_4"]='Manage Vlog';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_5"]='Edit forms';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_6"]='View forms messages';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_7"]='Manage content';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_8"]='Help Desk operator features';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_9"]='Help desk consultant features';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_10"]='Manage Our People';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_11"]='Unauthorized user features';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_12"]='See MADWWW side bar';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_13"]='See user info visible only for administrator';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_14"]='Edit any user profile';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_15"]='See registered users';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_16"]='Delete/Ban any user profile';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_22"]='Add/Delete Request Categories';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_23"]='Manage Newsletters';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_25"]='Edit Catalog';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_27"]='Manage Help Desk reports';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_30"]='Add users';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_31"]='Edit any user group';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_33"]='View All, Edit own, Add new solutions in Knowledge base';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_42"]='Add new record in FAQ';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_43"]='Delete record from FAQ';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_44"]='Edit records in FAQ';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_100"]='Edit content settings';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_200"]='Edit Help Desk settings';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_300"]='Manage Events';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_1900"]='Has access to Drive';//Название прав доступа пользователя
$uInt_processors_acl_name["acl_name_201"]='Manage Help Desk Company';//Название прав доступа пользователя