<?php
$uInt_processors_mod_title["uCore"]='Core';//Название модуля "Ядро" - основной модуль системы
$uInt_processors_mod_title["uConf"]='Settings';//Название модуля "Настройки" - настройки сайта
$uInt_processors_mod_title["uEditor"]='Texts';//Название модуля "Статьи" - статьи, тексты
$uInt_processors_mod_title["uAuth"]='Users';//Название модуля "Пользователи" - авторизация, профили пользователей
$uInt_processors_mod_title["uForms"]='Forms';//Название модуля "Формы" - формы
$uInt_processors_mod_title["uRubrics"]='Sections';//Название модуля "Рубрики" - рубрики содержат статьи. Например, новости
$uInt_processors_mod_title["common"]='Common';//Название модуля "Общие" - Общий модуль
$uInt_processors_mod_title["content"]='Content';//Название модуля "Контент" - Контент сайта. Слайдеры, тексты, страницы
$uInt_processors_mod_title["mainpage"]='Home page';//Название модуля "Главная" - Главная страница сайта
$uInt_processors_mod_title["uViblog"]='Vlog';//Название модуля "Видео лента"
$uInt_processors_mod_title["uPeople"]='Our People';//Название модуля "Наши люди"
$uInt_processors_mod_title["uCat"]='Catalog';//Название модуля "Каталог" - интернет-магазин
$uInt_processors_mod_title["uSup"]='Help Desk';//Название модуля "Техническая поддержка"
$uInt_processors_mod_title["uKnowbase"]='Knowledge base';//Название модуля "База знаний"
$uInt_processors_mod_title["uEvents"]='Events';//Название модуля "События"
$uInt_processors_mod_title["uSubscr"]='Newsletter';//Название модуля "Рассылки"
$uInt_processors_mod_title["advert"]='Adverts';//Название модуля "Объявления" - что-то типа avito
$uInt_processors_mod_title["obooking"]='Booking';//Название модуля "Записи, брони"
$uInt_processors_mod_title["gallery"]='Gallery';//Название модуля "Галерея"