<?php
$uInt_uEvents_event["Start date"]='Дата начала';//Таблица. Информации о дате события
$uInt_uEvents_event["Duration, days"]='Продолжительность, дней';//Таблица. Информации о дате события
$uInt_uEvents_event["Delete date"]='Удалить эту дату';//Заголовок Кнопки "Удалить эту дату"
$uInt_uEvents_event["Change date"]='Изменить дату';//Заголовок Кнопки "Изменить дату"
$uInt_uEvents_event["Where to set up this button?"]='Где настроить эту кнопку?';//Заголовок диалогового окошка, которое открывается при нажатии на иконку со знаком вопроса в блоке "Есть вопросы" (режим редактирования)
$uInt_uEvents_event["Have questions?"]='Есть вопросы?';//Заголовок блока
$uInt_uEvents_event["Contact us!"]='Свяжитесь с нами!';//Кнопка "Свяжитесь с нами"
$uInt_uEvents_event["New event title - dg title"]='Введите новое название события';//Заголовок диалога изменения названия события
$uInt_uEvents_event["Close - btn txt"]='Закрыть';//Кнопка "Закрыть" в диалогах
$uInt_uEvents_event["Save - btn txt"]='Сохранить';//Кнопка "Сохранить" в диалогах
$uInt_uEvents_event["Choose event type - dg title"]='Выберите новый тип события';//Заголовок диалога со сменой типа события
$uInt_uEvents_event["Files - dg title"]='Файлы';//Заголовок диалога со списком файлов события
$uInt_uEvents_event["Watch - btn txt"]='Просмотр';//Текст кнопки "Просмотр" в списке файлов
$uInt_uEvents_event["Insert - btn txt"]='Вставить';//Текст кнопки "Вставить" в списке файлов
$uInt_uEvents_event["Delete - btn txt"]='Удалить';//Текст кнопки "Удалить" в списке файлов
$uInt_uEvents_event["Delete All - btn txt"]='Удалить Все';//Текст кнопки "Удалить Все" в списке файлов
$uInt_uEvents_event["Add date - dg title"]='Добавить дату';//Заголовок диалога с добавлением даты события
$uInt_uEvents_event["Date - input label"]='Дата';//Подпись к полю "Дата" в диалоге добавления даты события
$uInt_uEvents_event["Duration - input label"]='Продолжительность';//Подпись к полю "Продолжительность" в диалоге добавления даты события
$uInt_uEvents_event["Duration - input dimension"]='дней';//Размерность к полю "Продолжительность" в диалоге добавления даты события. Например, 15 "дней"
$uInt_uEvents_event["Comment - input label"]='Комментарий';//Подпись к полю "Комментарий" в диалоге добавления даты события
$uInt_uEvents_event["Add - btn txt"]='Добавить';//Текст кнопки "Добавить" в диалогах
$uInt_uEvents_event["Assign form - dg title"]='Назначить форму';//Заголовок диалога "Назначить форму"
$uInt_uEvents_event["Assign code - dg title"]='Назначить код';//Заголовок диалога "Назначить код"
$uInt_uEvents_event["Code to assign - input label"]='Назначить код';//Подпись к полю "Код для вставки" в диалоге прикрепления кода к событию
$uInt_uEvents_event["Datepicker lang"]='ru';//Язык Datepicker
$uInt_uEvents_event["Select date btn"]='Выбрать';//Кнопка выбора даты события
$uInt_uEvents_event["Event page url editor - dg name"]='Редактор URL страницы события';//	Название диалога с редактором URL страницы
$uInt_uEvents_event["Fill the page url - label"]='Введите URL страницы события';//	Подпись к полю, в которое нужно ввести URL страницы
$uInt_uEvents_event["Event show dates - dg name"]='Даты показа события';//	Название диалога, в котором задаются даты показа события - в пределах этих дат событие будет отображаться на сайте, а потом будет скрыто
$uInt_uEvents_event["Event show dates - beginning - label"]='Начало';//	Подпись к выбору даты начала показа события в диалоге, в котором задаются даты показа события - в пределах этих дат событие будет отображаться на сайте, а потом будет скрыто
$uInt_uEvents_event["Event show dates - end - label"]='Конец';//	Подпись к выбору даты окончания показа события в диалоге, в котором задаются даты показа события - в пределах этих дат событие будет отображаться на сайте, а потом будет скрыто